let car = 'subaru';
console.log("Is car == 'subaru'? I predict true.");
console.log(car == 'subaru');
let fruit = 'grape';
console.log("Is fruit == 'mango'? I predict false.");
console.log(fruit == "mango");
let colour = "red";
console.log("Is colour == 'red'? I predict true.");
console.log(colour == 'red');
let country = "Turkey";
console.log("Is country == 'Korea'? I predict false.");
console.log(country == 'Korea');
let book = 'Harry Potter';
console.log("Is book == 'Harry Potter'? I predict true.");
console.log(book == 'Harry Potter');
let language = 'Arabic';
console.log("Is language == 'english'? I predict false.");
console.log(language == 'english');
let guest = 'Salar Sikandar';
console.log("Is guest == 'Salar Sikandar'? I predict true.");
console.log(guest == 'Salar Sikandar');
let currency = 'rupee';
console.log("Is currency == 'dollar'? I predict true.");
console.log(currency == 'dollar');
let mobile = 'iphone';
console.log("Is mobile == 'iphone'? I predict false.");
console.log(mobile == 'iphone');
let holiday = 'sunday';
console.log("Is holiday == 'friday'? I predict false.");
console.log(holiday == 'friday');
export {};
